apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: insignia-eks-cluster
  region: us-west-2
managedNodeGroups:
  - name: ng-1
    instanceType: t3.medium
    minSize: 1
    maxSize: 3
    desiredCapacity: 2
secretsEncryption:
  keyARN: arn:aws:kms:us-east-1:975049990844:key/1d981a5e-4f79-448f-9bec-1a21d48bb8eb