apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: insignia-app-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: insignia-app
  endpoints:
  - port: web
    interval: 15s